# api-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: aug12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: api-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: aug12
spec:
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

