# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL
#ENV MYSQL_ROOT_PASSWORD=password
#ENV MYSQL_DATABASE=testdb

# Copy the SQL script to initialize the database
COPY init.sql /docker-entrypoint-initdb.d/

